# Site settings
title: Welcome to Xiao Liu's Space!
description: A personal websie of Xiao Liu
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Xiao Liu
name: https://chriscliu.github.io
year: 2017
user_description: Currently, I am an undergraduate major in Computer Science in Shanghai Jiao Tong University. I graduated from Urumqi No.1 Senior High school, where I met my beloved. My research interest includes data mining, data analysis and all machine-learning related topics, especially in social networks.   
user_title: Undergraduate from SJTU
email: chrisliu9603@gmail.com
github_username:  ChrisCLiu
 
# Google-analytics
google-analytics:
  id: "UA-97687430-1"

exclude: ['package.json', 'src' , 'node_modules']
